agent/urls.py
from agent.views import signin

from django.urls import path
app_name='agent'

urlpatterns = [

    path('signin/', signin,name='signin'),
]

client/urls.py
from client.views import signin

from django.urls import path
app_name='client'

urlpatterns = [

    path('signin/', signin,name='signin'),
]

insurance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('agent/',include('agent.urls')),
    path('client/',include('client.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models

# Create your models here.
from agent.models import Agent
from account.models import MyUser
class Client(models.Model):
    Form_number = models.IntegerField(unique=True)
    Branch_name = models.CharField(max_length=200, null=True, blank=True)
    client_license_code = models.ForeignKey(Agent, on_delete=models.CASCADE, default=None,
                                            related_name='Client')#agent_licence code
    Name = models.CharField(max_length=200, null=True, blank=True)
    Gender_choices = (('Male', 'MALE'), ('Female', 'FEMALE'))
    gender = models.CharField(max_length=20, choices=Gender_choices, default=None)
    photo = models.ImageField(upload_to='uploads/', blank=True, null=True)
    Temporary_Address = models.CharField(max_length=200)
    Permanent_address = models.CharField(max_length=200)
    Contact_number = models.IntegerField()
    Email = models.EmailField(max_length=200, unique=True)
    password = models.CharField(max_length=200)
    Nationality = models.CharField(max_length=200)
    Education_level_choices = (('see', 'SEE'), ('Bachelors', 'BACHELORS'), ('Master', 'MASTER'))
    Education_level = models.CharField(max_length=200, choices=Education_level_choices, default=None)
    Citizenship = models.FileField(upload_to='uploads/',
                                   null=True, default="No file uploaded", blank=True)
    Citizenship_number = models.IntegerField(unique=True)
    Company_name = models.CharField(max_length=200)
    Company_location = models.CharField(max_length=200)
    Income_source = models.BigIntegerField()
    Fathers_name = models.CharField(max_length=200)
    Mothers_name = models.CharField(max_length=200)
    Grandfathers_name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    Date_of_birth = models.DateField()
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE,
                             related_name="clients")



    def __str__(self):
        return self.Name

client/forms.py
from django import forms

from policy.models import Applied_Policy


class SigninForm(forms.ModelForm):
    policy_id = forms.IntegerField()
    Date_of_birth = forms.DateTimeField()

    class Meta:
        model = Applied_Policy
        fields = ['policy_id', 'Date_of_birth']

client/views.py
from django.shortcuts import render

# Create your views here.
from client.forms import SigninForm


def signin(request):
    form=SigninForm
    return render(request,"client/signin.html",{"form":form})

templates/client/signin.html
{% extends "account/base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}


<title>{% block title %}Login To system{% endblock %}</title>
{% block content %}
    <div class="container">
    {% bootstrap_messages %}
    <div class="row">
        <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
                    Login to System
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                       <a href="{% url "client:signin" %}">client login</a>
                        <a href="{%url "agent:signin"  %}">Agent login</a>
                        {% bootstrap_form form %}
                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="login">


                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}